# 启动端口号
server:
  port: 9002

spring:
  # 解决SpringBoot 2.6.0 与swagger冲突问题，【原因是在SpringBoot2.6.0中将SpringMvc 默认路径匹配策略从AntPathMathCher 更改为PathPatternParser,导致出错，解决办法是切换回原来的AntPathMathCher】
  mvc:
    pathmatch:
      maching-strategy: ant_path_mathcher

  # 配置数据源
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置数据库连接属性
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhxy_db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool

  thymeleaf:
    # 模板的模式，支持 HTML XML TEXT JAVASCRIPT
    mode: HTML
    # 编码 可不用配置
    encoding: UTF-8
    # 开发配置为false，避免修改模板还要重启服务器
    cache: false
    # 配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/static/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    # 设置文件上传上限
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    # 添加日志文件
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
